// AUTH ACTION TYPES
export const TOKEN_CHECK_REQUEST = 'TOKEN_CHECK_REQUEST';
export const TOKEN_CHECK_SUCCESS = 'TOKEN_CHECK_SUCCESS';
export const TOKEN_CHECK_FAILURE = 'TOKEN_CHECK_FAILURE';

export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const USER_LOGOUT = 'USER_LOGOUT';

// LOGIN ACTION TYPES
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// SIGNUP ACTION TYPES
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
